// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number1 = 1;</code>
   */
  float getNumber1();

  /**
   * <code>float number2 = 2;</code>
   */
  float getNumber2();
}
