// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

public interface lightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightRequest)
    com.google.protobuf.MessageOrBuilder {
}
