// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
