// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListRequest)
    com.google.protobuf.MessageOrBuilder {
}
