// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
