// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

public final class SensorImpl {
  private SensorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempResponer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempResponer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service2.proto\"\035\n\013TempRequest\022\016\n\006numbe" +
      "r\030\001 \001(\t\",\n\014TempResponer\022\016\n\006number\030\001 \001(\t\022" +
      "\014\n\004base\030\002 \001(\005\"\016\n\014lightRequest\"\037\n\rLightRe" +
      "sponse\022\016\n\006number\030\001 \001(\005\"4\n\020CalculateReque" +
      "st\022\017\n\007number1\030\001 \001(\002\022\017\n\007number2\030\002 \001(\0022s\n\r" +
      "SensorService\022/\n\016ChangeRoomTemp\022\014.TempRe" +
      "quest\032\r.TempResponer\"\000\0221\n\016TurnOnOffLight" +
      "\022\r.lightRequest\032\016.LightResponse\"\000B\016B\nSen" +
      "sorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_TempResponer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TempResponer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempResponer_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_lightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightRequest_descriptor,
        new java.lang.String[] { });
    internal_static_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
