// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

public final class StorageServiceImpl {
  private StorageServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckFullStockrRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckFullStockrRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckFullStockResonse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckFullStockResonse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service3.proto\"(\n\026CheckFullStockrReque" +
      "st\022\016\n\006number\030\001 \001(\t\"5\n\025CheckFullStockReso" +
      "nse\022\016\n\006number\030\001 \001(\t\022\014\n\004base\030\002 \001(\005\"\r\n\013Lis" +
      "tRequest\"\036\n\014ListResponse\022\016\n\006number\030\001 \001(\005" +
      "\"4\n\020CalculateRequest\022\017\n\007number1\030\001 \001(\002\022\017\n" +
      "\007number2\030\002 \001(\0022\206\001\n\016StorageService\022C\n\016Che" +
      "ckFullStock\022\027.CheckFullStockrRequest\032\026.C" +
      "heckFullStockResonse\"\000\022/\n\016productChecker" +
      "\022\014.ListRequest\032\r.ListResponse\"\000B\026B\022Stora" +
      "geServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckFullStockrRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckFullStockrRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckFullStockrRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_CheckFullStockResonse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckFullStockResonse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckFullStockResonse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
