// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
