// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.UnaryString;

public interface ProductTranckerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartWareHouse.ProductTranckerRequest)
    com.google.protobuf.MessageOrBuilder {
}
