// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.UnaryString;

public interface ProductTrackerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartWareHouse.ProductTrackerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
