// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.UnaryString;

public final class RadioFrquencyIdenifierServiceImpl {
  private RadioFrquencyIdenifierServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartWareHouse_ScannerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartWareHouse_ScannerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartWareHouse_ScannerResponer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartWareHouse_ScannerResponer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartWareHouse_ProductTranckerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartWareHouse_ProductTranckerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartWareHouse_ProductTrackerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartWareHouse_ProductTrackerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartWareHouse_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartWareHouse_CalculateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service1.proto\022\016SmartWareHouse\" \n\016Scan" +
      "nerRequest\022\016\n\006number\030\001 \001(\t\"/\n\017ScannerRes" +
      "poner\022\016\n\006number\030\001 \001(\t\022\014\n\004base\030\002 \001(\005\"\030\n\026P" +
      "roductTranckerRequest\"(\n\026ProductTrackerR" +
      "esponse\022\016\n\006number\030\001 \001(\005\"4\n\020CalculateRequ" +
      "est\022\017\n\007number1\030\001 \001(\002\022\017\n\007number2\030\002 \001(\0022\324\001" +
      "\n\036RadioFrequencyIdenifierService\022b\n\016Prod" +
      "uctTracker\022&.SmartWareHouse.ProductTranc" +
      "kerRequest\032&.SmartWareHouse.ProductTrack" +
      "erResponse\"\000\022N\n\007Scanner\022\036.SmartWareHouse" +
      ".ScannerRequest\032\037.SmartWareHouse.Scanner" +
      "Responer\"\0000\001B7\n\020grpc.UnaryStringB!RadioF" +
      "rquencyIdenifierServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartWareHouse_ScannerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartWareHouse_ScannerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartWareHouse_ScannerRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_SmartWareHouse_ScannerResponer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartWareHouse_ScannerResponer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartWareHouse_ScannerResponer_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_SmartWareHouse_ProductTranckerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartWareHouse_ProductTranckerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartWareHouse_ProductTranckerRequest_descriptor,
        new java.lang.String[] { });
    internal_static_SmartWareHouse_ProductTrackerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartWareHouse_ProductTrackerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartWareHouse_ProductTrackerResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_SmartWareHouse_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartWareHouse_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartWareHouse_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
