// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package grpc.UnaryString;

public interface ScannerResponerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartWareHouse.ScannerResponer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>int32 base = 2;</code>
   */
  int getBase();
}
